opt_out_usage
default_platform(:ios)

platform :ios do
  desc "Build iOS app"
  lane :build do
    setup_ci if ENV['CI']
    cocoapods()
    set_info_plist_value(path: "wakawatch/Info.plist", key: "CFBundleVersion", value: ENV["APP_VERSION"])
    print get_info_plist_value(path: "wakawatch/Info.plist", key: "CFBundleVersion")

    set_info_plist_value(path: "wakawatch\ WatchKit\ App/Info.plist", key: "CFBundleVersion", value: ENV["APP_VERSION"])
    print get_info_plist_value(path: "wakawatch\ WatchKit\ App/Info.plist", key: "CFBundleVersion")

    set_info_plist_value(path: "wakawatch\ WatchKit\ Extension/Info.plist", key: "CFBundleVersion", value: ENV["APP_VERSION"])
    print get_info_plist_value(path: "wakawatch\ WatchKit\ Extension/Info.plist", key: "CFBundleVersion")

    # increment_build_number(xcodeproj: "wakawatch.xcodeproj")
    # build_app(workspace: "wakawatch.xcworkspace", scheme: "wakawatch")
  end
end
