opt_out_usage
default_platform(:ios)

platform :ios do
  desc "Build iOS app"
  lane :build do
    app_store_connect_api_key(
      key_id: "AQ5VCA4237",
      issuer_id: "1fbf6cf6-dd26-41f2-a459-b33d23051593",
      key_filepath: "./AuthKey_AQ5VCA4237.p8",
      duration: 1200,
      in_house: false
    )

    setup_ci if ENV['CI']
    cocoapods()
    app_version = "#{ENV["MAJOR"]}.#{ENV["MINOR"]}.#{ENV["PATCH"]}"

    increment_version_number(
      version_number: app_version,
      xcodeproj: "wakawatch.xcodeproj"
    )
    increment_build_number(
      build_number: ENV["BUILD_NUMBER"],
      xcodeproj: "wakawatch.xcodeproj"
    )
    match(
      type: "appstore",
      app_identifier: ["app.wakawatch", 
                       "app.wakawatch.watchkitapp",
                       "app.wakawatch.watchkitapp.watchkitextension"
                      ]
    )
    build_app(workspace: "wakawatch.xcworkspace", 
              scheme: "wakawatch", 
              export_method: "app-store",
              export_options: {
                provisioningProfiles: { 
                  "app.wakawatch" => "match AppStore app.wakawatch",
                  "app.wakawatch.watchkitapp" => "match AppStore app.wakawatch.watchkitapp",
                  "app.wakawatch.watchkitapp.watchkitextension" => "match AppStore app.wakawatch.watchkitapp.watchkitextension",
                }
              },
              output_directory: "./",
              output_name: "Waka-Watch",
            )
  end

  lane :deploy do
    app_store_connect_api_key(
      key_id: "AQ5VCA4237",
      issuer_id: "1fbf6cf6-dd26-41f2-a459-b33d23051593",
      key_filepath: "./AuthKey_AQ5VCA4237.p8",
      duration: 1200,
      in_house: false
    )
    
    app_version = "#{ENV["MAJOR"]}.#{ENV["MINOR"]}.#{ENV["PATCH"]}"

    upload_to_app_store(
      force: true,
      app_identifier: "app.wakawatch",
      ipa: "./Waka-Watch.ipa",
      app_version: app_version,
      skip_screenshots: true,
      automatic_release: true,
      reject_if_possible: true,
      submit_for_review: true,
      submission_information: {
        add_id_info_limits_tracking: true,
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: true,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: true,
        content_rights_has_rights: true,
        content_rights_contains_third_party_content: true,
        export_compliance_platform: 'ios',
        export_compliance_compliance_required: false,
        export_compliance_encryption_updated: false,
        export_compliance_app_type: nil,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: false,
        export_compliance_contains_third_party_cryptography: false,
        export_compliance_contains_proprietary_cryptography: false,
        export_compliance_available_on_french_store: false
      },
      precheck_include_in_app_purchases: false
    )
  end
end
