opt_out_usage
default_platform(:ios)

platform :ios do
  desc "Build iOS app"
  lane :build do
    app_store_connect_api_key(
      key_id: "AQ5VCA4237",
      issuer_id: "1fbf6cf6-dd26-41f2-a459-b33d23051593",
      key_filepath: "./fastlane/AuthKey_AQ5VCA4237.p8",
      duration: 1200,
      in_house: false
    )

    setup_ci if ENV['CI']
    cocoapods()
    set_info_plist_value(path: "wakawatch/Info.plist", key: "CFBundleVersion", value: ENV["APP_VERSION"])
    
    set_info_plist_value(path: "wakawatch\ WatchKit\ App/Info.plist", key: "CFBundleVersion", value: ENV["APP_VERSION"])
    
    set_info_plist_value(path: "wakawatch\ WatchKit\ Extension/Info.plist", key: "CFBundleVersion", value: ENV["APP_VERSION"])

    increment_build_number(xcodeproj: "wakawatch.xcodeproj")
    build_app(workspace: "wakawatch.xcworkspace", scheme: "wakawatch")
  end
end
