name: Build

on:
  push:
    branches:
      - "ci-cd"

jobs:
  Build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Bundle install
        run: |
          cd wakawatch
          bundle install

      - name:
        run: |
          cd wakawatch
          fastlane build
        env:
          CI: true
          APP_VERSION: "1.1"
