name: Build

on:
  push:
    branches:
      - "ci-cd"

jobs:
  Build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Bundle install
        run: |
          cd wakawatch
          bundle install

      - name: Configure git
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Decrypt sensitive files
        run: |
          cd wakawatch
          gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch Config.xcconfig.asc > ./wakawatch\ WatchKit\ Extension/Config.xcconfig
          gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch AuthKey_AQ5VCA4237.p8.asc > ./AuthKey_AQ5VCA4237.p8
          cat ./wakawatch\ WatchKit\ Extension/Config.xcconfig

      - name: Build
        run: |
          cd wakawatch
          bundle exec fastlane build
        env:
          CI: true
          APP_VERSION: "1.1"
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
