name: Build and Deploy

on:
  push:
    branches:
      - "ci-cd"
    tags:
      - "*"

jobs:
  Build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Run Bundle install
      #   run: |
      #     cd wakawatch
      #     bundle install

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: View App version
        run: |
          echo "APP_VERSION='$MAJOR.$MINOR'" >> $GITHUB_ENV
          echo $APP_VERSION
  #     - name: Configure git
  #       run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
  #       env:
  #         TOKEN: ${{ secrets.ACCESS_TOKEN }}

  #     - name: Decrypt sensitive files
  #       run: |
  #         cd wakawatch
  #         gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch Config.xcconfig.asc > ./wakawatch\ WatchKit\ Extension/Config.xcconfig
  #         gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch AuthKey_AQ5VCA4237.p8.asc > ./AuthKey_AQ5VCA4237.p8

  #     - name: Build
  #       run: |
  #         cd wakawatch
  #         bundle exec fastlane build
  #       env:
  #         CI: true
  #         APP_VERSION: $APP_VERSION
  #         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: Waka-Watch
  #         path: wakawatch/Waka-Watch.ipa

  # Deploy:
  #   runs-on: macOS-latest
  #   needs: Build
  #   if: startsWith(github.ref, 'refs/tags/')
  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: Waka-Watch
  #         path: wakawatch

  #     - name: Run Bundle install
  #       run: |
  #         cd wakawatch
  #         bundle install

  #     - name: Set app version
  #       if: startsWith(github.ref, 'refs/tags/')
  #       run: echo "APP_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

  #     - name: Decrypt sensitive files
  #       run: |
  #         cd wakawatch
  #         gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch AuthKey_AQ5VCA4237.p8.asc > ./AuthKey_AQ5VCA4237.p8

  #     - name: Deploy to App Store
  #       run: |
  #         cd wakawatch
  #         bundle exec fastlane deploy
  #       env:
  #         APP_VERSION: $APP_VERSION
