name: Build and Deploy

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  Build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
        name: Setup XCode

      - name: Run Bundle install
        run: |
          cd wakawatch
          bundle install

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Configure git
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Decrypt sensitive files
        run: |
          cd wakawatch
          gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch Config.xcconfig.asc > ./wakawatch\ WatchKit\ Extension/Config.xcconfig
          gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch AuthKey_AQ5VCA4237.p8.asc > ./AuthKey_AQ5VCA4237.p8

      - name: Build
        run: |
          cd wakawatch
          bundle exec fastlane build
        env:
          CI: true
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Waka-Watch
          path: wakawatch/Waka-Watch.ipa

  Deploy:
    runs-on: macOS-latest
    needs: Build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Waka-Watch
          path: wakawatch

      - name: Run Bundle install
        run: |
          cd wakawatch
          bundle install

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Decrypt sensitive files
        run: |
          cd wakawatch
          gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch AuthKey_AQ5VCA4237.p8.asc > ./AuthKey_AQ5VCA4237.p8

      - name: Deploy to App Store
        run: |
          cd wakawatch
          bundle exec fastlane deploy
